version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: barbershop-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: barbershop
    volumes:
      - ./pgdata:/var/lib/postgresql/data